### ISSUE TITLE
Tweepy Date Configuration Error

### ISSUE THREAD

**Issue by EmalineG** [EmalineG/Twitter-API-Query#1]
Console Output:

https://api.twitter.com/oauth/authorize?oauth_token=mlwArAAAAAABigazAAABhTsfWok
Provide your user pin from the link: 0142268
202201310000
Number of tweets in all_mentions dataframe: 200
202201250000
Number of tweets in all_mentions dataframe: 300
202201220000
Number of tweets in all_mentions dataframe: 400
202201190000
Number of tweets in all_mentions dataframe: 500
202201180000
Number of tweets in all_mentions dataframe: 600
202201170000
Number of tweets in all_mentions dataframe: 700
202201010000
Number of tweets in all_mentions dataframe: 755
Traceback (most recent call last):
  File "/Users/emalinemonique/getTweetData/getTweet.py", line 34, in <module>
    tweets_3_months = api.search_full_archive(label='dev',
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emalinemonique/getTweetData/.venv/lib/python3.11/site-packages/tweepy/api.py", line 33, in wrapper
    return method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emalinemonique/getTweetData/.venv/lib/python3.11/site-packages/tweepy/api.py", line 46, in wrapper
    return method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emalinemonique/getTweetData/.venv/lib/python3.11/site-packages/tweepy/api.py", line 453, in search_full_archive
    return self.request(
           ^^^^^^^^^^^^^
  File "/Users/emalinemonique/getTweetData/.venv/lib/python3.11/site-packages/tweepy/api.py", line 273, in request
    raise HTTPException(resp)
**tweepy.errors.HTTPException: 422 Unprocessable Entity
There were errors processing your request: Invalid 'fromDate':'202201010000'. 'fromDate' must be before 'toDate':202201010000**

**Comment by EmalineG** [comment]
Issue was that search_full_archive is exclusive to Premium Access. Reconfigured with search_tweets, which is the Elevated Access equivalent.
